graph TD
    KAFKA[Kafka KRaft] -->|service_healthy| KINIT[kafka-init]
    KINIT -->|service_completed_successfully| INV[inventory-service]
    KINIT -->|service_completed_successfully| ORD[order-service]
    KINIT -->|service_completed_successfully| PICK[picking-service]
    KINIT -->|service_completed_successfully| SHIP[shipping-service]
    KINIT -->|service_completed_successfully| INVSIM[inventory-simulator]
    KINIT -->|service_completed_successfully| SHIPSIM[shipping-simulator]
    KINIT -->|service_completed_successfully| ORDSIM[order-simulator]
    KINIT -->|service_completed_successfully| PICKSIM[picking-simulator]

    INVDB[inventory-db] -->|service_started| INV
    ORDDB[order-db] -->|service_started| ORD
    PICKDB[picking-db] -->|service_started| PICK
    SHIPDB[shipping-db] -->|service_started| SHIP
    INBDB[inbound-db] -->|service_started| INVSIM
    SSDB[shipping-sim-db] -->|service_started| SHIPSIM
    OSDB[order-sim-db] -->|service_started| ORDSIM
    PSDB[picking-sim-db] -->|service_started| PICKSIM

    INV -->|service_started| FE[frontend]
    ORD -->|service_started| FE
    PICK -->|service_started| FE
    SHIP -->|service_started| FE
    ORDSIM -->|service_started| FE
    PICKSIM -->|service_started| FE
    INVSIM -->|service_started| FE
    KAFKA -->|service_healthy| FE
    KINIT -->|service_completed_successfully| FE

    OO[OpenObserve] -->|service_started| FB[Fluent Bit]
