graph TD
    KAFKA[Kafka KRaft] --> KINIT[kafka-init]
    KINIT --> INV[inventory-service]
    KINIT --> ORD[order-service]
    KINIT --> PICK[picking-service]
    KINIT --> SHIP[shipping-service]
    INV --> INVSIM[inventory-simulator]
    SHIP --> SHIPSIM[shipping-simulator]
    INV --> ORDSIM[order-simulator]
    ORD --> ORDSIM
    PICK --> PICKSIM[picking-simulator]

    INVDB[inventory-db] --> INV
    ORDDB[order-db] --> ORD
    PICKDB[picking-db] --> PICK
    SHIPDB[shipping-db] --> SHIP

    INV --> FE[frontend]
    ORD --> FE
    PICK --> FE
    SHIP --> FE
    ORDSIM --> FE
    PICKSIM --> FE
    INVSIM --> FE
    KAFKA --> FE
    KINIT --> FE

    FB[Fluent Bit] --> OO[OpenObserve]
