sequenceDiagram
    autonumber
    participant UI as Frontend / Simulator
    participant ORD as Order Service
    participant INV as Inventory Service
    participant PICK as Picking Service
    participant SHIP as Shipping Service
    participant DISP as Shipping Simulator

    UI->>ORD: POST /orders (PlaceOrder)
    ORD->>INV: OrderPlaced
    
    alt Stock sufficiente
        INV->>ORD: InventoryAllocated
        ORD->>PICK: OrderReadyForPicking
        PICK->>PICK: PickingTaskCreated
        
        UI->>PICK: POST /picking/tasks/:id/complete
        PICK->>ORD: PickingTaskCompleted
        PICK->>SHIP: PickingTaskCompleted
        SHIP->>ORD: ShipmentAssigned
        
        DISP->>SHIP: POST /shipping/vehicles/:id/dispatch
        SHIP->>SHIP: VehicleDispatched
    else Stock insufficiente
        INV->>ORD: OutOfStock
        ORD->>ORD: OrderSuspended
    end
