[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224

[FILTER]
    Name          modify
    Match         *
    Add           source docker
    Add           deployment whs-local

[FILTER]
    Name          grep
    Match         *
    Exclude       log .*\[(NestFactory|InstanceLoader|RoutesResolver|RouterExplorer|NestApplication|NestMicroservice|ServerKafka|ClientKafka|MongooseCoreModule|MongooseModule)\].*
    Exclude       log ^$

[FILTER]
    Name          lua
    Match         *
    script        /fluent-bit/etc/clean_ansi.lua
    call          clean_ansi

[OUTPUT]
    Name              http
    Match             *
    Host              openobserve
    Port              5080
    URI               /api/default/whs_logs/_json
    tls               Off
    Format            json
    Json_date_key     _timestamp
    Json_date_format  iso8601
    HTTP_User         root@example.com
    HTTP_Passwd       Complexpass#123
    compress          gzip
